###
## Typus Configuration File
##
#
# Post:
#   fields:
#     list: id, title, category_id, created_at, is_published?
#     form: title, body, is_published?, created_at
#     relationship: title, status
#     options:
#       selectors:
#       read_only:
#       auto_generated:
#       date_formats:
#         created_at: post_long
#       booleans:
#         is_published: ["Yes, it is", "No, it isn't"]
#   actions:
#     index: cleanup
#     edit: send_as_newsletter
#     show: rebuild
#   export: csv, xml, pdf
#   order_by: created_at
#   relationships:
#   filters: is_published?, created_at, category_id
#   search: title, body
#   application: Application
#   description: Some text to describe the model
#   options:
#     edit_after_create: false
#     end_year: 2015
#     form_rows: 25
#     icon_on_boolean: true
#     minute_step: 15
#     nil: 'nil'
#     per_page: 5
#     sidebar_selector: 5
#     start_year: 1990
#     toggle: true
#
###
<%- ar_models.each do |model| -%>
<%- list = model.columns.reject { |c| c.sql_type == 'text' }.map(&:name) -%>
<%- form = model.columns.reject { |c| c.name == 'id' }.map(&:name) -%>
<%- relationships = [] -%>
<%- [:belongs_to, :has_and_belongs_to_many, :has_many].each do |relationship| -%>
 <%- relationships += model.reflect_on_all_associations(relationship).map { |i| i.name.to_s } -%>
<%- end -%>

<%= model %>:
  fields:
    list: <%= list.map.join(', ') %>
    form: <%= form.map.join(', ') %>
    relationship:
    options:
      selectors:
      read_only:
      auto_generated:
  actions:
    index:
    edit:
  export:
  order_by:
  relationships: <%= relationships.sort.join(', ') %>
  filters:
  search:
  application: <%= application %>
  description:
<%- end -%>